version: "3"

services:
  cache:
    image: "redis:7.0.5-alpine"
    ports:
      - "6379:6379"
  db:
    image: "postgres:15rc2-alpine"
    environment:
      POSTGRES_DB: "critter"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - "data:/var/lib/postgres/data"

volumes:
  data:
