version: "3"

services:
  cache:
    image: "redis:7.0.5-alpine"
    ports:
      - "6379:6379"
  db:
    image: "mariadb:10.9.3"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "critter"
      MYSQL_USER: "critter"
      MYSQL_PASSWORD: "critter"
    ports:
      - "3306:3306"
    restart: "always"
    volumes:
      - "data:/var/lib/mysql"

volumes:
  data:
