// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SqueaksColumns holds the columns for the "squeaks" table.
	SqueaksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SqueaksTable holds the schema information for the "squeaks" table.
	SqueaksTable = &schema.Table{
		Name:       "squeaks",
		Columns:    SqueaksColumns,
		PrimaryKey: []*schema.Column{SqueaksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "address", Type: field.TypeString, Size: 42},
		{Name: "username", Type: field.TypeString, Size: 32},
		{Name: "status", Type: field.TypeInt8, Default: 0},
		{Name: "scout_level", Type: field.TypeInt8, Default: 1},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SqueaksTable,
		UsersTable,
	}
)

func init() {
}
