// Code generated by ent, DO NOT EDIT.

package squeak

const (
	// Label holds the string label denoting the squeak type in the database.
	Label = "squeak"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlockNumber holds the string denoting the block_number field in the database.
	FieldBlockNumber = "block_number"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// Table holds the table name of the squeak in the database.
	Table = "squeaks"
)

// Columns holds all SQL columns for squeak fields.
var Columns = []string{
	FieldID,
	FieldBlockNumber,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
)
