// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ahashim/web-server/ent/pool"
	"github.com/ahashim/web-server/ent/poolpass"
	"github.com/ahashim/web-server/ent/predicate"
	"github.com/ahashim/web-server/ent/squeak"
	"github.com/ahashim/web-server/types"
)

// PoolUpdate is the builder for updating Pool entities.
type PoolUpdate struct {
	config
	hooks    []Hook
	mutation *PoolMutation
}

// Where appends a list predicates to the PoolUpdate builder.
func (pu *PoolUpdate) Where(ps ...predicate.Pool) *PoolUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdateTime sets the "update_time" field.
func (pu *PoolUpdate) SetUpdateTime(t time.Time) *PoolUpdate {
	pu.mutation.SetUpdateTime(t)
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PoolUpdate) SetAmount(t *types.Uint256) *PoolUpdate {
	pu.mutation.SetAmount(t)
	return pu
}

// SetShares sets the "shares" field.
func (pu *PoolUpdate) SetShares(t *types.Uint256) *PoolUpdate {
	pu.mutation.SetShares(t)
	return pu
}

// AddPoolPassIDs adds the "pool_passes" edge to the PoolPass entity by IDs.
func (pu *PoolUpdate) AddPoolPassIDs(ids ...int) *PoolUpdate {
	pu.mutation.AddPoolPassIDs(ids...)
	return pu
}

// AddPoolPasses adds the "pool_passes" edges to the PoolPass entity.
func (pu *PoolUpdate) AddPoolPasses(p ...*PoolPass) *PoolUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddPoolPassIDs(ids...)
}

// SetSqueakID sets the "squeak" edge to the Squeak entity by ID.
func (pu *PoolUpdate) SetSqueakID(id int) *PoolUpdate {
	pu.mutation.SetSqueakID(id)
	return pu
}

// SetNillableSqueakID sets the "squeak" edge to the Squeak entity by ID if the given value is not nil.
func (pu *PoolUpdate) SetNillableSqueakID(id *int) *PoolUpdate {
	if id != nil {
		pu = pu.SetSqueakID(*id)
	}
	return pu
}

// SetSqueak sets the "squeak" edge to the Squeak entity.
func (pu *PoolUpdate) SetSqueak(s *Squeak) *PoolUpdate {
	return pu.SetSqueakID(s.ID)
}

// Mutation returns the PoolMutation object of the builder.
func (pu *PoolUpdate) Mutation() *PoolMutation {
	return pu.mutation
}

// ClearPoolPasses clears all "pool_passes" edges to the PoolPass entity.
func (pu *PoolUpdate) ClearPoolPasses() *PoolUpdate {
	pu.mutation.ClearPoolPasses()
	return pu
}

// RemovePoolPassIDs removes the "pool_passes" edge to PoolPass entities by IDs.
func (pu *PoolUpdate) RemovePoolPassIDs(ids ...int) *PoolUpdate {
	pu.mutation.RemovePoolPassIDs(ids...)
	return pu
}

// RemovePoolPasses removes "pool_passes" edges to PoolPass entities.
func (pu *PoolUpdate) RemovePoolPasses(p ...*PoolPass) *PoolUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemovePoolPassIDs(ids...)
}

// ClearSqueak clears the "squeak" edge to the Squeak entity.
func (pu *PoolUpdate) ClearSqueak() *PoolUpdate {
	pu.mutation.ClearSqueak()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PoolUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	pu.defaults()
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PoolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PoolUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PoolUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PoolUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PoolUpdate) defaults() {
	if _, ok := pu.mutation.UpdateTime(); !ok {
		v := pool.UpdateDefaultUpdateTime()
		pu.mutation.SetUpdateTime(v)
	}
}

func (pu *PoolUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pool.Table,
			Columns: pool.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pool.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdateTime(); ok {
		_spec.SetField(pool.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(pool.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Shares(); ok {
		_spec.SetField(pool.FieldShares, field.TypeInt, value)
	}
	if pu.mutation.PoolPassesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedPoolPassesIDs(); len(nodes) > 0 && !pu.mutation.PoolPassesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PoolPassesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.SqueakCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pool.SqueakTable,
			Columns: []string{pool.SqueakColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: squeak.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.SqueakIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pool.SqueakTable,
			Columns: []string{pool.SqueakColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: squeak.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PoolUpdateOne is the builder for updating a single Pool entity.
type PoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PoolMutation
}

// SetUpdateTime sets the "update_time" field.
func (puo *PoolUpdateOne) SetUpdateTime(t time.Time) *PoolUpdateOne {
	puo.mutation.SetUpdateTime(t)
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PoolUpdateOne) SetAmount(t *types.Uint256) *PoolUpdateOne {
	puo.mutation.SetAmount(t)
	return puo
}

// SetShares sets the "shares" field.
func (puo *PoolUpdateOne) SetShares(t *types.Uint256) *PoolUpdateOne {
	puo.mutation.SetShares(t)
	return puo
}

// AddPoolPassIDs adds the "pool_passes" edge to the PoolPass entity by IDs.
func (puo *PoolUpdateOne) AddPoolPassIDs(ids ...int) *PoolUpdateOne {
	puo.mutation.AddPoolPassIDs(ids...)
	return puo
}

// AddPoolPasses adds the "pool_passes" edges to the PoolPass entity.
func (puo *PoolUpdateOne) AddPoolPasses(p ...*PoolPass) *PoolUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddPoolPassIDs(ids...)
}

// SetSqueakID sets the "squeak" edge to the Squeak entity by ID.
func (puo *PoolUpdateOne) SetSqueakID(id int) *PoolUpdateOne {
	puo.mutation.SetSqueakID(id)
	return puo
}

// SetNillableSqueakID sets the "squeak" edge to the Squeak entity by ID if the given value is not nil.
func (puo *PoolUpdateOne) SetNillableSqueakID(id *int) *PoolUpdateOne {
	if id != nil {
		puo = puo.SetSqueakID(*id)
	}
	return puo
}

// SetSqueak sets the "squeak" edge to the Squeak entity.
func (puo *PoolUpdateOne) SetSqueak(s *Squeak) *PoolUpdateOne {
	return puo.SetSqueakID(s.ID)
}

// Mutation returns the PoolMutation object of the builder.
func (puo *PoolUpdateOne) Mutation() *PoolMutation {
	return puo.mutation
}

// ClearPoolPasses clears all "pool_passes" edges to the PoolPass entity.
func (puo *PoolUpdateOne) ClearPoolPasses() *PoolUpdateOne {
	puo.mutation.ClearPoolPasses()
	return puo
}

// RemovePoolPassIDs removes the "pool_passes" edge to PoolPass entities by IDs.
func (puo *PoolUpdateOne) RemovePoolPassIDs(ids ...int) *PoolUpdateOne {
	puo.mutation.RemovePoolPassIDs(ids...)
	return puo
}

// RemovePoolPasses removes "pool_passes" edges to PoolPass entities.
func (puo *PoolUpdateOne) RemovePoolPasses(p ...*PoolPass) *PoolUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemovePoolPassIDs(ids...)
}

// ClearSqueak clears the "squeak" edge to the Squeak entity.
func (puo *PoolUpdateOne) ClearSqueak() *PoolUpdateOne {
	puo.mutation.ClearSqueak()
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PoolUpdateOne) Select(field string, fields ...string) *PoolUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pool entity.
func (puo *PoolUpdateOne) Save(ctx context.Context) (*Pool, error) {
	var (
		err  error
		node *Pool
	)
	puo.defaults()
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PoolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Pool)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PoolMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PoolUpdateOne) SaveX(ctx context.Context) *Pool {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PoolUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PoolUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PoolUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdateTime(); !ok {
		v := pool.UpdateDefaultUpdateTime()
		puo.mutation.SetUpdateTime(v)
	}
}

func (puo *PoolUpdateOne) sqlSave(ctx context.Context) (_node *Pool, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pool.Table,
			Columns: pool.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pool.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pool.FieldID)
		for _, f := range fields {
			if !pool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdateTime(); ok {
		_spec.SetField(pool.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(pool.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Shares(); ok {
		_spec.SetField(pool.FieldShares, field.TypeInt, value)
	}
	if puo.mutation.PoolPassesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedPoolPassesIDs(); len(nodes) > 0 && !puo.mutation.PoolPassesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PoolPassesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pool.PoolPassesTable,
			Columns: []string{pool.PoolPassesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: poolpass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.SqueakCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pool.SqueakTable,
			Columns: []string{pool.SqueakColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: squeak.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.SqueakIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pool.SqueakTable,
			Columns: []string{pool.SqueakColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: squeak.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pool{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
