// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ahashim/web-server/ent/poolpass"
	"github.com/ahashim/web-server/ent/predicate"
)

// PoolPassQuery is the builder for querying PoolPass entities.
type PoolPassQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PoolPass
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PoolPassQuery builder.
func (ppq *PoolPassQuery) Where(ps ...predicate.PoolPass) *PoolPassQuery {
	ppq.predicates = append(ppq.predicates, ps...)
	return ppq
}

// Limit adds a limit step to the query.
func (ppq *PoolPassQuery) Limit(limit int) *PoolPassQuery {
	ppq.limit = &limit
	return ppq
}

// Offset adds an offset step to the query.
func (ppq *PoolPassQuery) Offset(offset int) *PoolPassQuery {
	ppq.offset = &offset
	return ppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppq *PoolPassQuery) Unique(unique bool) *PoolPassQuery {
	ppq.unique = &unique
	return ppq
}

// Order adds an order step to the query.
func (ppq *PoolPassQuery) Order(o ...OrderFunc) *PoolPassQuery {
	ppq.order = append(ppq.order, o...)
	return ppq
}

// First returns the first PoolPass entity from the query.
// Returns a *NotFoundError when no PoolPass was found.
func (ppq *PoolPassQuery) First(ctx context.Context) (*PoolPass, error) {
	nodes, err := ppq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{poolpass.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppq *PoolPassQuery) FirstX(ctx context.Context) *PoolPass {
	node, err := ppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PoolPass ID from the query.
// Returns a *NotFoundError when no PoolPass ID was found.
func (ppq *PoolPassQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{poolpass.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppq *PoolPassQuery) FirstIDX(ctx context.Context) int {
	id, err := ppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PoolPass entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PoolPass entity is found.
// Returns a *NotFoundError when no PoolPass entities are found.
func (ppq *PoolPassQuery) Only(ctx context.Context) (*PoolPass, error) {
	nodes, err := ppq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{poolpass.Label}
	default:
		return nil, &NotSingularError{poolpass.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppq *PoolPassQuery) OnlyX(ctx context.Context) *PoolPass {
	node, err := ppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PoolPass ID in the query.
// Returns a *NotSingularError when more than one PoolPass ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppq *PoolPassQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{poolpass.Label}
	default:
		err = &NotSingularError{poolpass.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppq *PoolPassQuery) OnlyIDX(ctx context.Context) int {
	id, err := ppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PoolPasses.
func (ppq *PoolPassQuery) All(ctx context.Context) ([]*PoolPass, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ppq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ppq *PoolPassQuery) AllX(ctx context.Context) []*PoolPass {
	nodes, err := ppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PoolPass IDs.
func (ppq *PoolPassQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ppq.Select(poolpass.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppq *PoolPassQuery) IDsX(ctx context.Context) []int {
	ids, err := ppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppq *PoolPassQuery) Count(ctx context.Context) (int, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ppq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ppq *PoolPassQuery) CountX(ctx context.Context) int {
	count, err := ppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppq *PoolPassQuery) Exist(ctx context.Context) (bool, error) {
	if err := ppq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ppq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ppq *PoolPassQuery) ExistX(ctx context.Context) bool {
	exist, err := ppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PoolPassQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppq *PoolPassQuery) Clone() *PoolPassQuery {
	if ppq == nil {
		return nil
	}
	return &PoolPassQuery{
		config:     ppq.config,
		limit:      ppq.limit,
		offset:     ppq.offset,
		order:      append([]OrderFunc{}, ppq.order...),
		predicates: append([]predicate.PoolPass{}, ppq.predicates...),
		// clone intermediate query.
		sql:    ppq.sql.Clone(),
		path:   ppq.path,
		unique: ppq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Shares *types.Uint256 `json:"shares,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PoolPass.Query().
//		GroupBy(poolpass.FieldShares).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppq *PoolPassQuery) GroupBy(field string, fields ...string) *PoolPassGroupBy {
	grbuild := &PoolPassGroupBy{config: ppq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ppq.sqlQuery(ctx), nil
	}
	grbuild.label = poolpass.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Shares *types.Uint256 `json:"shares,omitempty"`
//	}
//
//	client.PoolPass.Query().
//		Select(poolpass.FieldShares).
//		Scan(ctx, &v)
func (ppq *PoolPassQuery) Select(fields ...string) *PoolPassSelect {
	ppq.fields = append(ppq.fields, fields...)
	selbuild := &PoolPassSelect{PoolPassQuery: ppq}
	selbuild.label = poolpass.Label
	selbuild.flds, selbuild.scan = &ppq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a PoolPassSelect configured with the given aggregations.
func (ppq *PoolPassQuery) Aggregate(fns ...AggregateFunc) *PoolPassSelect {
	return ppq.Select().Aggregate(fns...)
}

func (ppq *PoolPassQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ppq.fields {
		if !poolpass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppq.path != nil {
		prev, err := ppq.path(ctx)
		if err != nil {
			return err
		}
		ppq.sql = prev
	}
	return nil
}

func (ppq *PoolPassQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PoolPass, error) {
	var (
		nodes = []*PoolPass{}
		_spec = ppq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PoolPass).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PoolPass{config: ppq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ppq *PoolPassQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppq.querySpec()
	_spec.Node.Columns = ppq.fields
	if len(ppq.fields) > 0 {
		_spec.Unique = ppq.unique != nil && *ppq.unique
	}
	return sqlgraph.CountNodes(ctx, ppq.driver, _spec)
}

func (ppq *PoolPassQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ppq *PoolPassQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   poolpass.Table,
			Columns: poolpass.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: poolpass.FieldID,
			},
		},
		From:   ppq.sql,
		Unique: true,
	}
	if unique := ppq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ppq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, poolpass.FieldID)
		for i := range fields {
			if fields[i] != poolpass.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppq *PoolPassQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppq.driver.Dialect())
	t1 := builder.Table(poolpass.Table)
	columns := ppq.fields
	if len(columns) == 0 {
		columns = poolpass.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppq.sql != nil {
		selector = ppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppq.unique != nil && *ppq.unique {
		selector.Distinct()
	}
	for _, p := range ppq.predicates {
		p(selector)
	}
	for _, p := range ppq.order {
		p(selector)
	}
	if offset := ppq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PoolPassGroupBy is the group-by builder for PoolPass entities.
type PoolPassGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppgb *PoolPassGroupBy) Aggregate(fns ...AggregateFunc) *PoolPassGroupBy {
	ppgb.fns = append(ppgb.fns, fns...)
	return ppgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ppgb *PoolPassGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ppgb.path(ctx)
	if err != nil {
		return err
	}
	ppgb.sql = query
	return ppgb.sqlScan(ctx, v)
}

func (ppgb *PoolPassGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ppgb.fields {
		if !poolpass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ppgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ppgb *PoolPassGroupBy) sqlQuery() *sql.Selector {
	selector := ppgb.sql.Select()
	aggregation := make([]string, 0, len(ppgb.fns))
	for _, fn := range ppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ppgb.fields)+len(ppgb.fns))
		for _, f := range ppgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ppgb.fields...)...)
}

// PoolPassSelect is the builder for selecting fields of PoolPass entities.
type PoolPassSelect struct {
	*PoolPassQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pps *PoolPassSelect) Aggregate(fns ...AggregateFunc) *PoolPassSelect {
	pps.fns = append(pps.fns, fns...)
	return pps
}

// Scan applies the selector query and scans the result into the given value.
func (pps *PoolPassSelect) Scan(ctx context.Context, v any) error {
	if err := pps.prepareQuery(ctx); err != nil {
		return err
	}
	pps.sql = pps.PoolPassQuery.sqlQuery(ctx)
	return pps.sqlScan(ctx, v)
}

func (pps *PoolPassSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(pps.fns))
	for _, fn := range pps.fns {
		aggregation = append(aggregation, fn(pps.sql))
	}
	switch n := len(*pps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		pps.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		pps.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := pps.sql.Query()
	if err := pps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
