// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ahashim/web-server/ent/poolpass"
	"github.com/ahashim/web-server/types"
)

// PoolPassCreate is the builder for creating a PoolPass entity.
type PoolPassCreate struct {
	config
	mutation *PoolPassMutation
	hooks    []Hook
}

// SetShares sets the "shares" field.
func (ppc *PoolPassCreate) SetShares(t *types.Uint256) *PoolPassCreate {
	ppc.mutation.SetShares(t)
	return ppc
}

// Mutation returns the PoolPassMutation object of the builder.
func (ppc *PoolPassCreate) Mutation() *PoolPassMutation {
	return ppc.mutation
}

// Save creates the PoolPass in the database.
func (ppc *PoolPassCreate) Save(ctx context.Context) (*PoolPass, error) {
	var (
		err  error
		node *PoolPass
	)
	if len(ppc.hooks) == 0 {
		if err = ppc.check(); err != nil {
			return nil, err
		}
		node, err = ppc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PoolPassMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ppc.check(); err != nil {
				return nil, err
			}
			ppc.mutation = mutation
			if node, err = ppc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ppc.hooks) - 1; i >= 0; i-- {
			if ppc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ppc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ppc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PoolPass)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PoolPassMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ppc *PoolPassCreate) SaveX(ctx context.Context) *PoolPass {
	v, err := ppc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppc *PoolPassCreate) Exec(ctx context.Context) error {
	_, err := ppc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppc *PoolPassCreate) ExecX(ctx context.Context) {
	if err := ppc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppc *PoolPassCreate) check() error {
	if _, ok := ppc.mutation.Shares(); !ok {
		return &ValidationError{Name: "shares", err: errors.New(`ent: missing required field "PoolPass.shares"`)}
	}
	return nil
}

func (ppc *PoolPassCreate) sqlSave(ctx context.Context) (*PoolPass, error) {
	_node, _spec := ppc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ppc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ppc *PoolPassCreate) createSpec() (*PoolPass, *sqlgraph.CreateSpec) {
	var (
		_node = &PoolPass{config: ppc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: poolpass.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: poolpass.FieldID,
			},
		}
	)
	if value, ok := ppc.mutation.Shares(); ok {
		_spec.SetField(poolpass.FieldShares, field.TypeInt, value)
		_node.Shares = value
	}
	return _node, _spec
}

// PoolPassCreateBulk is the builder for creating many PoolPass entities in bulk.
type PoolPassCreateBulk struct {
	config
	builders []*PoolPassCreate
}

// Save creates the PoolPass entities in the database.
func (ppcb *PoolPassCreateBulk) Save(ctx context.Context) ([]*PoolPass, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ppcb.builders))
	nodes := make([]*PoolPass, len(ppcb.builders))
	mutators := make([]Mutator, len(ppcb.builders))
	for i := range ppcb.builders {
		func(i int, root context.Context) {
			builder := ppcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PoolPassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ppcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ppcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ppcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ppcb *PoolPassCreateBulk) SaveX(ctx context.Context) []*PoolPass {
	v, err := ppcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppcb *PoolPassCreateBulk) Exec(ctx context.Context) error {
	_, err := ppcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppcb *PoolPassCreateBulk) ExecX(ctx context.Context) {
	if err := ppcb.Exec(ctx); err != nil {
		panic(err)
	}
}
