// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"github.com/ahashim/web-server/enums"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// EdgeInteractions holds the string denoting the interactions edge name in mutations.
	EdgeInteractions = "interactions"
	// EdgePoolPasses holds the string denoting the pool_passes edge name in mutations.
	EdgePoolPasses = "pool_passes"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// EdgeCreated holds the string denoting the created edge name in mutations.
	EdgeCreated = "created"
	// EdgeOwned holds the string denoting the owned edge name in mutations.
	EdgeOwned = "owned"
	// EdgeFollowers holds the string denoting the followers edge name in mutations.
	EdgeFollowers = "followers"
	// EdgeFollowing holds the string denoting the following edge name in mutations.
	EdgeFollowing = "following"
	// Table holds the table name of the user in the database.
	Table = "users"
	// InteractionsTable is the table that holds the interactions relation/edge.
	InteractionsTable = "interactions"
	// InteractionsInverseTable is the table name for the Interaction entity.
	// It exists in this package in order to avoid circular dependency with the "interaction" package.
	InteractionsInverseTable = "interactions"
	// InteractionsColumn is the table column denoting the interactions relation/edge.
	InteractionsColumn = "user_interactions"
	// PoolPassesTable is the table that holds the pool_passes relation/edge.
	PoolPassesTable = "pool_passes"
	// PoolPassesInverseTable is the table name for the PoolPass entity.
	// It exists in this package in order to avoid circular dependency with the "poolpass" package.
	PoolPassesInverseTable = "pool_passes"
	// PoolPassesColumn is the table column denoting the pool_passes relation/edge.
	PoolPassesColumn = "user_pool_passes"
	// RolesTable is the table that holds the roles relation/edge. The primary key declared below.
	RolesTable = "user_roles"
	// RolesInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolesInverseTable = "roles"
	// CreatedTable is the table that holds the created relation/edge.
	CreatedTable = "squeaks"
	// CreatedInverseTable is the table name for the Squeak entity.
	// It exists in this package in order to avoid circular dependency with the "squeak" package.
	CreatedInverseTable = "squeaks"
	// CreatedColumn is the table column denoting the created relation/edge.
	CreatedColumn = "user_created"
	// OwnedTable is the table that holds the owned relation/edge.
	OwnedTable = "squeaks"
	// OwnedInverseTable is the table name for the Squeak entity.
	// It exists in this package in order to avoid circular dependency with the "squeak" package.
	OwnedInverseTable = "squeaks"
	// OwnedColumn is the table column denoting the owned relation/edge.
	OwnedColumn = "user_owned"
	// FollowersTable is the table that holds the followers relation/edge. The primary key declared below.
	FollowersTable = "user_following"
	// FollowingTable is the table that holds the following relation/edge. The primary key declared below.
	FollowingTable = "user_following"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldAddress,
	FieldUsername,
	FieldStatus,
	FieldLevel,
}

var (
	// RolesPrimaryKey and RolesColumn2 are the table columns denoting the
	// primary key for the roles relation (M2M).
	RolesPrimaryKey = []string{"user_id", "role_id"}
	// FollowersPrimaryKey and FollowersColumn2 are the table columns denoting the
	// primary key for the followers relation (M2M).
	FollowersPrimaryKey = []string{"user_id", "follower_id"}
	// FollowingPrimaryKey and FollowingColumn2 are the table columns denoting the
	// primary key for the following relation (M2M).
	FollowingPrimaryKey = []string{"user_id", "follower_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int8
)

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enums.Status) error {
	switch s.String() {
	case "UNKNOWN", "ACTIVE", "SUSPENDED", "BANNED":
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for status field: %q", s)
	}
}
