// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Squeak is the predicate function for squeak builders.
type Squeak func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
