// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Interaction is the predicate function for interaction builders.
type Interaction func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Scout is the predicate function for scout builders.
type Scout func(*sql.Selector)

// ScoutPool is the predicate function for scoutpool builders.
type ScoutPool func(*sql.Selector)

// Squeak is the predicate function for squeak builders.
type Squeak func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
